---
name: IO-Moose
version: 0.08
author:
  - 'Piotr Roszatycki <dexter@debian.org>'
abstract: Reimplementation of IO::* with improvements
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IO-Moose
  license: http://dev.perl.org/licenses/
  repository: http://dexter-cpan.googlecode.com/svn/IO-Moose
requires:
  Exception::Argument: 0
  Exception::Base: 0.21
  Exception::Died: 0
  Exception::Fatal: 0
  Exception::System: 0.11
  File::Stat::Moose: 0.03
  MooseX::GlobRef::Object: 0.05
  Task::Weaken: 0
  Test::Assert: 0.04
  constant::boolean: 0
  maybe: 0
  perl: 5.008
build_requires:
  Exception::Warning: 0
  Taint::Runtime: 0
  Test::Unit::Lite: 0.11
  parent: 0
provides:
  IO::Moose:
    file: lib/IO/Moose.pm
    version: 0.08
  IO::Moose::File:
    file: lib/IO/Moose/File.pm
    version: 0.08
  IO::Moose::Handle:
    file: lib/IO/Moose/Handle.pm
    version: 0.08
  IO::Moose::Seekable:
    file: lib/IO/Moose/Seekable.pm
    version: 0.08
  MooseX::Types::CanonOpenModeStr:
    file: lib/MooseX/Types/CanonOpenModeStr.pm
    version: 0.08
  MooseX::Types::OpenModeStr:
    file: lib/MooseX/Types/OpenModeStr.pm
    version: 0.08
  MooseX::Types::OpenModeWithLayerStr:
    file: lib/MooseX/Types/OpenModeWithLayerStr.pm
    version: 0.08
  MooseX::Types::PerlIOLayerStr:
    file: lib/MooseX/Types/PerlIOLayerStr.pm
    version: 0.08
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
